---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    colours:
      - red
      - green
      - blue
      - yellow
      - black
      - white
    maxturns: 12
  tasks:
    - name: Select the colour of four pegs.
      include_tasks: peg-colour.yml
      loop: [ 0, 1, 2, 3 ]
      loop_control:
        loop_var: peg_number
      when: pegs is not defined

    - debug:
        msg: >
          To play the game you have to run the playbook successively using the
          option --extra-var to define the guess variable.
          For example: --extra-var "guess=blue,black,yellow,red"
      when: 'guess is not defined'

    - set_fact:
        __guess: "{{  guess.split(',') }}"
      when: 'guess is defined'

    - name: Increase turn number.
      set_fact:
        turns: "{{ turns | default(0) | int + 1 }}"
        cacheable: yes

    - name: It's the end!
      file:
        path: .facts/localhost
        state: absent
      when: 'turns | int == maxturns'
