---
dependency:
  name: galaxy
  enabled: false
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: /usr/local/bin/python3
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
