---
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - debug:
        msg: "Real play through - set II"

    - set_fact:
        pegs: [ "red", "black", "green", "red" ]

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses: [ "black", "green", "red", "red" ]
    - name: Turn I
      assert:
        that:
          - bulls|int == 1
          - cows|int == 3

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses: [ "red", "green", "black", "red" ]
    - name: Turn II
      assert:
        that:
          - bulls|int == 2
          - cows|int == 2
