---
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - debug:
        msg: "Real play through - set I"

    - set_fact:
        pegs: [ "white", "green", "green", "white" ]

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - green
          - green
          - green
          - green
    - assert:
        that:
          - bulls|int == 2
          - cows|int == 0

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - green
          - green
          - white
          - white
    - assert:
        that:
          - bulls|int == 2
          - cows|int == 2

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - white
          - white
          - green
          - green
    - assert:
        that:
          - bulls|int == 2
          - cows|int == 2

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - green
          - white
          - white
          - green
    - assert:
        that:
          - bulls|int == 0
          - cows|int == 4

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - white
          - green
          - green
          - blue
    - assert:
        that:
          - bulls|int == 3
          - cows|int == 0
