---
- hosts: all
  become: no
  gather_facts: no
  vars:
    pegs:
      "0": red
      "1": black
      "2": green
      "3": red
  tasks:
    - debug:
        msg: "Real play through - set I"

    - set_fact:
        pegs: { "0": red, "1": black, "2": green, "3": red }

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - black
          - green
          - red
          - red
    - assert:
        that:
          - bulls|int == 1
          - cows|int == 3

    - include_tasks: ../../bull-or-cow.yml
      vars:
        guesses:
          - red
          - green
          - black
          - red

    - assert:
        that:
          - bulls|int == 2
          - cows|int == 2
