---
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - debug:
        msg: "Artificial placement tests - set I"

    - block:
        - set_fact:
            pegs: [ "red", "red", "red", "red" ]
        - include_tasks: ../../bull-or-cow.yml
          vars:
            guesses:
              - red
              - red
              - red
              - red
        - assert:
            that:
              - bulls|int == 4
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "red", "red", "black", "red" ]
        - include_tasks: ../../bull-or-cow.yml
          vars:
            guesses:
              - red
              - red
              - red
              - red
        - assert:
            that:
              - bulls|int == 3
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "red", "green", "black", "red" ]
        - include_tasks: ../../bull-or-cow.yml
          vars:
            guesses:
              - red
              - red
              - red
              - red
        - assert:
            that:
              - bulls|int == 2
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "red", "green", "black", "yellow" ]
        - include_tasks: ../../bull-or-cow.yml
          vars:
            guesses:
              - red
              - red
              - red
              - red
        - assert:
            that:
              - bulls|int == 1
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "blue", "green", "black", "yellow" ]
        - include_tasks: ../../bull-or-cow.yml
          vars:
            guesses:
              - red
              - red
              - red
              - red
        - assert:
            that:
              - bulls|int == 0
              - cows|int == 0
