---
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - debug:
        msg: "Artificial placement tests - set I"

    - block:
        - set_fact:
            pegs: [ "red", "red", "red", "red" ]
            guesses: [ "red", "red", "red", "red" ]
        - include_tasks: ../../bull-or-cow.yml
        - name: Four bulls.
          assert:
            that:
              - bulls|int == 4
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "red", "red", "black", "red" ]
            guesses: [ "red", "red", "red", "red" ]
        - include_tasks: ../../bull-or-cow.yml
        - name: Three bulls.
          assert:
            that:
              - bulls|int == 3
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "red", "green", "black", "red" ]
            guesses: [ "red", "red", "red", "red" ]
        - include_tasks: ../../bull-or-cow.yml
        - name: Two bulls.
          assert:
            that:
              - bulls|int == 2
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "red", "green", "black", "yellow" ]
            guesses: [ "red", "red", "red", "red" ]
        - include_tasks: ../../bull-or-cow.yml
        - name: One bull.
          assert:
            that:
              - bulls|int == 1
              - cows|int == 0

    - block:
        - set_fact:
            pegs: [ "blue", "green", "black", "yellow" ]
        - include_tasks: ../../bull-or-cow.yml
        - name: Zero bulls.
          assert:
            that:
              - bulls|int == 0
              - cows|int == 0
